/* Главы 4–7: время, волна маркетплейсов, две линзы, проверка. */
const wave = DATA.wave, cleanup = DATA.cleanup, checks = DATA.checks;
const dmpScale = d3.scaleSequential(d3.interpolateBlues).domain([0, 8]);
const legendDmp = () => [[0.5, '0–1 п.п.'], [3, '3'], [5, '5'], [7.5, '7 п.п. и больше']].map(([v, l]) => ({ color: dmpScale(v), label: l }));
/* геометрия штрих-кода: слева — колонка подписей типов, снизу — месяцы */
const barcodeBox = st => { const x = st.w < 780 ? 84 : 182; return { x, y: st.top + 22, w: st.w - x - 24, h: st.h - st.top - st.chartBottom - 44 }; };
/* подписи: тип, сколько МО и сколько из них меняли тип; пунктир отделяет менявших (они отсортированы вверх группы) */
function barcodeAxes(svg, st) {
  const { x, y, w, h } = barcodeBox(st); const narrow = st.w < 780;
  const g = svg.append('g').attr('font-family', 'inherit');
  const ax = g.append('g').attr('font-size', 11.5).attr('fill', cssVar('--muted'));
  [0, 6, 12, 18, 23].forEach(t => ax.append('text').attr('x', x + (t + 0.5) * w / 24).attr('y', y + h + 17).attr('text-anchor', 'middle').text(fmt.month(MONTHS[t])));
  let yy = y;
  [0, 1, 2, 3].forEach(k => {
    const size = T.macro.sizes[k]; const hh = h * size / N;
    const moved = MO.filter(m => m.ma === k && m.sw[0] > 0).length;
    if (k > 0) g.append('line').attr('x1', x).attr('x2', x + w).attr('y1', yy).attr('y2', yy).attr('stroke', cssVar('--bg')).attr('stroke-width', 2);
    if (moved) { const hm = hh * moved / size; g.append('line').attr('x1', x).attr('x2', x + w).attr('y1', yy + hm).attr('y2', yy + hm).attr('stroke', cssVar('--ink')).attr('stroke-opacity', 0.45).attr('stroke-dasharray', '5,4'); }
    const lab = g.append('text').attr('x', x - 12).attr('y', yy + hh / 2).attr('text-anchor', 'end');
    lab.append('tspan').attr('x', x - 12).attr('font-size', narrow ? 10.5 : 12).attr('font-weight', 650).attr('fill', cssVar('--ink')).text(narrow ? (SHORT_TYPE[nameOf.macro(k)] || nameOf.macro(k)) : nameOf.macro(k));
    lab.append('tspan').attr('x', x - 12).attr('dy', 15).attr('font-size', narrow ? 10 : 11).attr('fill', cssVar('--muted')).text(narrow ? `меняли ${moved}` : `${size} МО · меняли ${moved}`);
    yy += hh;
  });
}
const monthView = (t, extra = {}) => ({ title: 'Макротипы по месяцам', sub: fmt.month(MONTHS[t]) + ' · цвет — тип в этом месяце', map: { mode: 'macro', month: t }, dots: { layout: 'hidden' }, legend: legendMacro(), ...extra });
let curMonth = 0, monthWarm = 0, waveT = 1;

CHAPTERS.push(
  { id: 'time', title: 'Состояния во времени', steps: [
    { text: `<p>Типы посчитаны для каждого из 24 месяцев с учётом истории. Листайте медленно: карта проигрывает два года. Большинство территорий не меняют цвет вовсе, переключения — редкие и точечные.</p><p class="note">KEFRiN-T: вес истории оценивается по данным (AFFECT), у каждого МО есть устойчивый эффект, а настоящая смена типа проходит без задержки благодаря тесту инновации.</p>`,
      view: s => { curMonth = 0; return monthView(0); },
      progress: (p, st) => { const t = Math.round(p * 23); if (t !== curMonth) { curMonth = t; st.setView(monthView(t), { soft: true }); clearTimeout(monthWarm); monthWarm = setTimeout(() => { if (t < 23) st.warm(monthView(t + 1)); }, 70); } } },
    { text: `<p>Все 2 016 историй разом: каждая строка — муниципалитет, каждый столбец — месяц, цвет — тип. <b class="num">${fmt.pct(MO.filter(m => m.sw[0] === 0).length / N)}</b> строк одноцветны: тип не менялся ни разу. Смены сосредоточены на границах сельского типа и малых городов.</p>`,
      view: s => ({ title: 'Штрих-код: 2 016 историй типа', sub: s.w < 780 ? 'строки — МО, столбцы — месяцы; пунктир — кто менял тип' : 'строки — МО по типам, столбцы — месяцы; пунктир — граница тех, кто менял тип', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: legendMacro(),
        wipe: true,
        paint: (ctx, st) => { const b = barcodeBox(st); Charts.barcode(ctx, { ...b, lens: 'macro', dpr: st.map.dpr }); },
        svg: (svg, st) => barcodeAxes(svg, st) }),
      progress: (p, st) => st.setWipe(0.06 + 1.3 * p) },
    { text: `<p>Потоки между типами по полугодиям. Толстые ленты — те, кто остался; тонкие — переходы. Больше всего движения между сельским типом и городами: это соседние состояния.</p><p class="note">Диагональ месячной матрицы переходов 0,96–0,997; ожидаемое пребывание в типе — от 25 месяцев у северных до десятков лет у столичных агломераций.</p>`,
      progress: (p, st) => { if (st.flowClip) st.flowClip.attr('width', Math.min(1, 0.12 + 1.35 * p) * st.flowW); },
      view: s => ({ title: 'Потоки между макротипами', sub: s.w < 780 ? 'январь 2023 → декабрь 2024, по годам' : 'январь 2023 → декабрь 2024, по полугодиям', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: legendMacro(), svg: (svg, st) => { const g0 = svg.append('g');
        Charts.flows(g0, { x: st.w < 780 ? 12 : 40, y: st.top, w: st.w - (st.w < 780 ? 24 : 80), h: st.h - st.top - st.chartBottom, lens: 'macro', narrow: st.w < 780 });
        st.flowClip = Charts.clip(svg, g0, { x: 0, y: 0, w: st.w, h: st.h }); st.flowW = st.w; st.flowClip.attr('width', st.w * 0.12); } }) },
    { text: `<p>Первый проход алгоритма «усаживал» типологию в первые месяцы и давал всплеск смен в июне 2023 года. Второй проход — старт от модальных типов первого — убирает переходный процесс: смен за два года стало на <b class="num">23%</b> меньше, а сами типы не изменились у 99% территорий. Ноябрь и декабрь по-прежнему дают больше смен: новогодний сдвиг структуры трат.</p>`,
      view: s => ({ title: 'Смены типа по месяцам: до и после второго прохода', sub: 'макротипы', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: [{ color: isDark() ? '#5a5b62' : '#c9c8c3', label: 'до: старт по первым 3 месяцам' }, { color: MACRO_C[0], label: 'после: второй проход' }],
        svg: (svg, st) => { const { g, iw, ih } = Charts.frame(svg, { x: 20, y: st.top, w: st.w - 40, h: st.h - st.top - st.chartBottom, ml: 44, mr: 16, mt: 20, mb: 40 }); const months = cleanup.months; const b = cleanup.switches.K4_before, a = cleanup.switches.K4_after; const xs = d3.scaleBand().domain(months).range([0, iw]).padding(0.25); const ys = d3.scaleLinear().domain([0, d3.max(b) * 1.1]).range([ih, 0]).nice(); Charts.axisY(g, ys, iw); months.forEach((m, i) => { const bw = xs.bandwidth() / 2; g.append('rect').attr('x', xs(m)).attr('y', ys(b[i])).attr('width', bw - 1).attr('height', ih - ys(b[i])).attr('rx', 2).attr('fill', isDark() ? '#5a5b62' : '#c9c8c3'); g.append('rect').attr('x', xs(m) + bw).attr('y', ys(a[i])).attr('width', bw - 1).attr('height', ih - ys(a[i])).attr('rx', 2).attr('fill', MACRO_C[0]); if (i % 3 === 0) g.append('text').attr('x', xs(m) + xs.bandwidth() / 2).attr('y', ih + 18).attr('text-anchor', 'middle').attr('font-size', 11.5).attr('fill', cssVar('--muted')).text(fmt.month(m)); }); annotate(g, xs('2023-06') + xs.bandwidth() / 4, ys(b[months.indexOf('2023-06')]), 'июнь 2023: 78 → 36', { dy: -12 }); } }) },
  ] },
  { id: 'wave', title: 'Волна маркетплейсов', steps: [
    { text: `<p>Типы устойчивы, но внутри них структура трат сдвинулась в одну сторону: доля маркетплейсов <b>удвоилась</b> — с ${fmt.pct(wave.kpi.mean_share_first, 1)} в январе 2023 до ${fmt.pct(wave.kpi.mean_share_last, 1)} в декабре 2024. Листайте: линии дорисовываются по месяцам. Пик 2023 года — ноябрь, в 2024-м у городов и столиц он сдвинулся на декабрь.</p>`,
      view: s => { waveT = 1; return { title: 'Доля маркетплейсов в тратах по типам', sub: 'среднее по МО типа', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: legendMacro(), svg: (svg, st) => Charts.lines(svg, { x: 10, y: st.top, w: st.w - 20, h: st.h - st.top - st.chartBottom, series: [0, 1, 2, 3].map(k => wave.series['type' + k + '_mean'].map(v => v * 100)), xs: [0, 23], ys: [5, 22], colors: MACRO_C, labels: ['Города', 'Север', 'Столичные агломерации', 'Село'], upto: waveT, fmtY: v => v + '%', ghost: true }) }; },
      progress: (p, st) => { const t = 1 + p * 22; if (Math.abs(t - waveT) > 0.02) { waveT = t; st.redrawOverlay(); } } },
    { text: `<p>Прирост доли за год на карте. Быстрее всего растут отдалённые сельские районы Сибири и Дальнего Востока с низкой стартовой долей: Мотыгинский район на Енисее — с 4,6% до 19,5%. Медленнее всего — два полюса: арктические районы Якутии и Чукотки, где доставки почти нет, и центр Москвы, где она не нужна.</p>`,
      view: s => ({ title: 'Прирост доли маркетплейсов за год', sub: 'среднее 2024 − среднее 2023, процентные пункты', map: { mode: 'custom', color: i => MO[i].dmp == null ? null : dmpScale(MO[i].dmp) }, dots: { layout: 'hidden' }, legend: legendDmp(), tip: i => `<b>${esc(MO[i].n)}</b><span class="muted">${esc(MO[i].r)}</span><div class="row"><span>доля 2023 → 2024</span><span>${fmt.pct(MO[i].mp23, 1)} → ${fmt.pct(MO[i].mp24, 1)}</span></div><div class="row"><span>прирост</span><span>${fmt.pp(MO[i].dmp)}</span></div>` }) },
    { text: `<p>Это догоняющий рост: чем ниже стартовая доля и чем меньше население и зарплата, тем быстрее растёт онлайн. Сельские МО уже в 2023 году тратили на маркетплейсах больше столиц, а к 2024-му — ${fmt.pct(wave.by_type['Сельские и малые'].share_2024_median / 100, 1)} против ${fmt.pct(wave.by_type['Столичные агломерации'].share_2024_median / 100, 1)}: онлайн замещает отсутствующую офлайн-торговлю.</p><p class="note">Эффект дорожной доступности рынков меняет знак при добавлении региональных эффектов и не считается установленным.</p>`,
      view: s => ({ title: 'Стартовая доля и прирост', sub: 'каждая точка — МО, цвет — макротип', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: legendMacro(), svg: (svg, st) => Charts.scatter(svg, { x: 10, y: st.top, w: st.w - 20, h: st.h - st.top - st.chartBottom, xv: i => MO[i].mp23 == null ? null : MO[i].mp23 * 100, yv: i => MO[i].dmp, color: i => MACRO_C[MO[i].ma], xsDom: [0, 25], ysDom: [0, 16], xLabel: 'доля маркетплейсов в 2023 году, %', yLabel: 'прирост доли за год, п.п.', fmtX: v => v + '%', fmtY: v => v, annotate: [{ x: 4.6, y: 14.9, text: 'Мотыгинский район: 4,6% → 19,5%', dx: 80, dy: -8, anchor: 'start' }] }) }) },
    { text: `<p>Между типами доли расходятся, а внутри двух самых массовых типов — сходятся: тест сходимости log-t не отвергает её для сельского и северного типов, но отвергает для городов и столиц. Типология задаёт клубы сходимости и для структуры трат.</p>`,
      view: s => ({ title: 'Прирост доли маркетплейсов по типам', sub: 'медиана и межквартильный размах, п.п. за год', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: [], svg: (svg, st) => Charts.bars(svg, { x: 40, y: st.top, w: Math.min(st.w - 80, 760), h: st.h - st.top - st.chartBottom, items: [3, 1, 0, 2].map(k => { const b = wave.by_type[T.macro.names[k]]; return { label: T.macro.names[k], v: b.d_share_pp_median, lo: b.d_share_pp_q25, hi: b.d_share_pp_q75, color: MACRO_C[k] }; }), fmtV: v => fmt.num(v, 1), yLabel: 'п.п.' }) }) },
  ] },
  { id: 'lenses', title: 'Две линзы', steps: [
    { text: `<p>Экономическая типология строится на потреблении вместе с контекстом Росстата. Что в ней от данных СберИндекса? Статическая кластеризация только по контексту воспроизводит типы с ARI ${fmt.num(T.lens.halves['только контекст'])}, только по потреблению — ${fmt.num(T.lens.halves['только потребление'])}, вместе — ${fmt.num(T.lens.halves['полные признаки'])}.</p>`,
      view: s => ({ title: 'Экономическая линза: макротипы', sub: 'потребление + контекст Росстата', map: { mode: 'macro', month: 23 }, dots: { layout: 'hidden' }, legend: legendMacro() }) },
    { text: `<p>Поэтому есть вторая линза — <b>поведенческая</b>: тот же метод, но только по структуре и уровню трат, без Росстата. Пять «корзин»: общепит и услуги, базовая корзина малых городов, продукты и маркетплейсы, транспортная корзина и дорогая корзина без онлайна. Карта перекрашивается: столицы и Север совпадают в обеих линзах, село распадается на три корзины.</p><p class="note">Правила на сырых долях: общепит больше 5% — «общепит и услуги»; маркетплейсы меньше 12% — «дорогая корзина без онлайна»; транспорт больше 6% — «транспортная корзина».</p>`,
      view: s => ({ title: 'Поведенческая линза: пять корзин', sub: 'только данные СберИндекса', map: { mode: 'beh', month: 23 }, dots: { layout: 'hidden' }, legend: legendBeh() }) },
    { text: `<p>Ленты показывают, как одно делится на другое. Экономическая линза отвечает «какая это территория», поведенческая — «как здесь тратят», и вторая не выводится из первой: согласие линз ARI ${fmt.num(T.lens.ari)}.</p>`,
      view: s => ({ title: 'Как экономические типы распадаются на корзины', sub: 'число МО в каждой ленте', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: [], svg: (svg, st) => Charts.ribbons(svg, { x: 20, y: st.top + 14, w: st.w - 40, h: st.h - st.top - st.chartBottom - 20 }) }) },
  ] },
  { id: 'checks', title: 'Проверка', steps: [
    { text: `<p>Метод проверен на синтетических сетях с 15% «мигрантов» в шестой месяц KEFRiN-T ловит ${fmt.pct((checks.synthetic.find(r => r.s_e === 'calibrated' && r.method === 'kefrin_t_affect_fe_z2.5') || {})['movers_correct_+0'] || 0)} смен сразу и почти 90% через два месяца при доле ложных смен меньше 1%. Версия без теста инновации замечала бы лишь 5% сразу.</p>`,
      view: s => ({ title: 'Синтетическая проверка: доля пойманных смен', sub: 'калиброванный сценарий, через 0 / 1 / 2 месяца после события', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: [{ color: MACRO_C[0], label: 'сразу' }, { color: mix(MACRO_C[0], 0.4), label: 'через месяц' }, { color: mix(MACRO_C[0], 0.68), label: 'через два' }],
        svg: (svg, st) => { const rows = [['KEFRiN-T (итог)', 'kefrin_t_affect_fe_z2.5'], ['без теста инновации', 'kefrin_t_affect_fe_noreset'], ['AFFECT, блочная модель', 'kefrin_t_affect'], ['K-means по месяцам', 'kmeans_monthly'], ['temporal Leiden', 'temporal_leiden_w1.0']].map(([l, m]) => ({ label: l, r: checks.synthetic.find(r => r.s_e === 'calibrated' && r.method === m) })).filter(d => d.r); const { g, iw, ih } = Charts.frame(svg, { x: 20, y: st.top, w: st.w - 40, h: st.h - st.top - st.chartBottom, ml: 190, mr: 60, mt: 16, mb: 30 }); const ys = d3.scaleBand().domain(rows.map(d => d.label)).range([0, ih]).padding(0.3); const xs = d3.scaleLinear().domain([0, 1]).range([0, iw]); Charts.axisX(g, xs, ih, { ticks: 5, fmt: v => Math.round(v * 100) + '%' }); rows.forEach(d => { const bh = ys.bandwidth() / 3; ['movers_correct_+0', 'movers_correct_+1', 'movers_correct_+2'].forEach((key, j) => { const v = d.r[key]; g.append('rect').attr('x', 0).attr('y', ys(d.label) + j * bh).attr('width', xs(v)).attr('height', bh - 2).attr('rx', 3).attr('fill', j === 0 ? MACRO_C[0] : mix(MACRO_C[0], j === 1 ? 0.4 : 0.68)); g.append('text').attr('x', xs(v) + 6).attr('y', ys(d.label) + j * bh + bh / 2 + 4).attr('font-size', 11).attr('fill', cssVar('--ink')).text(Math.round(v * 100) + '%'); }); g.append('text').attr('x', -10).attr('y', ys(d.label) + ys.bandwidth() / 2 + 4).attr('text-anchor', 'end').attr('font-size', 12).attr('font-weight', 600).attr('fill', cssVar('--ink-2')).text(d.label); g.append('text').attr('x', -10).attr('y', ys(d.label) + ys.bandwidth() / 2 + 18).attr('text-anchor', 'end').attr('font-size', 11).attr('fill', cssVar('--muted')).text('ложных смен ' + fmt.pct(d.r.false_switch_at_event, 1)); }); } }) },
    { text: `<p>Число типов выбрано по устойчивости: при K = 4 бутстрап-ARI ${fmt.num(checks.stability.find(r => r.K === 4).ari_mean)}, при K = 6 — ${fmt.num(checks.stability.find(r => r.K === 6).ari_mean)}, дальше устойчивость падает. Два контрольных прогона с нуля воспроизвели итоговые типы побайтно. Весь пайплайн — одна команда <code>make all</code>.</p>`,
      view: s => ({ title: 'Устойчивость по числу типов', sub: 'bootstrap-ARI, 20 подвыборок по 80% МО', map: { mode: 'none' }, dots: { layout: 'hidden' }, legend: [], svg: (svg, st) => Charts.bars(svg, { x: 40, y: st.top, w: Math.min(st.w - 80, 700), h: st.h - st.top - st.chartBottom, items: checks.stability.map(r => ({ label: 'K = ' + r.K, v: r.ari_mean, color: r.K === 4 ? MACRO_C[0] : (isDark() ? '#5a5b62' : '#c9c8c3') })), fmtV: v => fmt.num(v, 2), yLabel: 'ARI' }) }) },
    { text: `<p>Дальше — интерактивная часть: карта по месяцам и линзам, паспорт любого муниципалитета и сопоставимые ему территории. Всё считается из тех же файлов результатов, что и отчёт.</p>`,
      view: s => ({ title: 'Четыре типа местных экономик России', sub: 'декабрь 2024', map: { mode: 'macro', month: 23 }, dots: { layout: 'hidden' }, legend: legendMacro() }) },
  ] },
);
